In [1]:
import numpy as np

a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
#sum 및 axis
a.sum()     # 모든 요소들의 합
a.sum(axis=0) # 행의 합 -세로    1   2   3   4
a.sum(axis=1) # 열의 합 -가로    5   6   7   8
                #               9   10  11  12

array([10, 26, 42])

In [6]:
np.sum(a[1])

26

In [10]:
a.min(axis=0)
a.max(axis=0)
a.mean(axis=0)#평균

array([5., 6., 7., 8.])

In [11]:
#sorting

b=np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [12]:
np.sort(b)  #axis=1
b.sort()
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [18]:
b.sort(axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [20]:
#내림차순 
c=np.array([42,38,12,25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [21]:
np.argsort(c)   # 내림차순으로 값이 아니라 그 값의 인덱스 주소를 출력


array([2, 3, 1, 0], dtype=int64)

In [22]:
# sigmoid 함수

def sigmoid(x):
    return 1./(1+np.exp(-x))


In [24]:
X=np.array([-10,0,10])
sigmoid(X)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

In [25]:
b.T

array([[ 1,  1,  3],
       [ 2,  4,  9],
       [ 5,  5, 11],
       [ 7, 12, 14]])

In [61]:
#Concatenate
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [27]:
b=np.array([5,6])
b

array([5, 6])

In [40]:

np.vstack((a,b))    #2개의 배열 합치기 위로쌓기


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.hstack((a,b))#옆으로 쌓기

In [67]:
# Array operation
a*a
a/a
a+a

array([[2, 4],
       [6, 8]])

In [68]:
a+3


array([[4, 5],
       [6, 7]])

In [70]:
a=np.arange(1,7).reshape(2,3)        # 1 2 3    7 8
                                     # 4 5 6    9 10 
b=np.arange(7,13).reshape(3,2)               # 11  12
                                    # (1*7+2*9+3*11) ,(1*8+2*10+3*12)        
                                    # (4*7+5*9+6*11) ,(4*8+5*10+6*12)



In [71]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [72]:
#comparision 비교

a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [75]:
np.any(a>5) # 하나라도 참이면 참
np.all(a>5) # 모두가 참이어야 참

False

In [76]:
# Ligical operation
b= np.logical_and(a>3,a<7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [77]:
b=np.logical_or(a>7,a<3)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

In [78]:
#Boolean & Fancy indexing

#boolean indexing
a[b]   #  위의 ligical함수와 연계 -조건이 참인 index의 값만 추출

array([4, 5, 6])

In [81]:
#fancy indexing

a=np.array([2,4,6,8])
b=np.array([0,0,1,3,2,1])   # a의 index 값
a[b]


array([2, 2, 4, 8, 6, 4])

In [82]:
# 기술 통계

a=np.random.randn(10)
a

array([ 1.09603519,  0.05465488,  1.1175141 , -1.50336307,  1.54374782,
        0.66638114, -1.81812836, -0.80445426, -1.54658556,  0.80556129])

In [83]:
# 평균
np.mean(a),a.mean()

(-0.03886368323376612, -0.03886368323376612)

In [84]:
# 표준편차(standard deviation)
np.std(a),a.std()

(1.204945192650096, 1.204945192650096)

In [86]:
#최소 ,최대
a.min(),a.max()

(-1.8181283624832283, 1.543747823401079)

In [87]:
# 4분위수
np.percentile(a,25),np.percentile(a,50),np.percentile(a,75)

(-1.3286358675136742, 0.3605180106543903, 1.0234167137955974)

In [88]:
# 중앙값

np.median(a)

0.3605180106543903

In [90]:
a=np.random.randint(0,3,100)
a
# 0, 1, 2의 갯수
np.unique(a,return_counts=True) #중복되는 값의 갯수 추출

(array([0, 1, 2]), array([33, 43, 24], dtype=int64))