In [1]:
import numpy as np

In [8]:
num=np.arange(10,90,10).reshape(2,4)



array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [166]:
m = np.array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])
m[1,2]
m[2,4]
m[1,1:3]
m[1:2,2:],m[2:3,:3]
m[0:2,3:5]

(array([[7, 8, 9]]), array([[10, 11, 12]]))

In [93]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x3 = x%3 ==0
x4=x%4==1
x5=(x%3==0)&(x%4==1)


array([9])

In [168]:
3*np.eye(5,5,k=-1,dtype=int)+2*np.eye(5,5,k=0,dtype=int)+np.eye(5,5,k=1,dtype=int)


array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [136]:
from numpy import random
n=10 * random.random_sample(size=(5,6))
n.max()
n.sum(axis=1)
np.max(n, axis=1)
np.mean(n,axis=0)
np.min(n,axis=0)


array([1.66940668e+00, 2.24543347e+00, 5.77042472e+00, 3.93291964e+00,
       1.73583898e-03, 3.01229488e+00])

In [162]:
n=np.array([[ 1, 2, 3, 4],
            [ 46, 99, 100, 71],
            [ 81, 59, 90, 100]])

a=np.argsort(n)[1:2,::-1]
n=n[:,a]
n


array([[[  3,   2,   4,   1]],

       [[100,  99,  71,  46]],

       [[ 90,  59, 100,  81]]])

In [164]:
n=np.random.randint(1,7,size=100)
print(n.mean())

3.41


In [165]:
np.random.randn(250)

array([ 3.19036919e-01, -4.29354239e-01, -4.54661171e-03, -1.57937314e+00,
        8.47795162e-01, -3.45994002e-01,  9.86629688e-01,  4.25686137e-01,
       -1.68664671e+00, -6.00072144e-01, -3.16011981e-01,  1.28213317e+00,
       -5.02450213e-01, -3.58520150e-01, -1.22354903e+00, -5.19040893e-01,
       -8.23552112e-01,  1.26483391e-01,  1.21627361e+00, -8.68161808e-01,
       -1.49485709e+00, -7.27622890e-02, -9.15216069e-01,  1.96271886e-01,
        1.34935124e+00,  3.96438278e-01,  8.95485257e-02,  1.09921108e+00,
       -8.24943085e-01,  8.49132966e-01,  6.17848905e-01,  2.08044305e-01,
        2.58188065e-01,  4.93772466e-01,  5.06502348e-01,  6.67774671e-01,
        5.42102383e-01,  2.04353588e+00,  1.13474582e-01,  1.95288121e-01,
       -9.10068664e-01, -2.22759525e+00, -1.25447612e+00, -3.97246853e-02,
        1.13113828e+00,  1.53893536e+00,  4.01691975e-02, -3.46709340e-01,
        1.72170398e+00, -5.10865791e-01,  5.48189095e-01, -7.62098030e-01,
       -7.40272939e-01,  