In [3]:
import numpy as np

In [8]:
num=np.arange(10,90,10).reshape(2,4)



array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [11]:
m = np.array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])
m[1,2]
m[2,4]
m[1 ,1:3]
m[1:, 2]
m[0:2, 3:5]

array([ 7, 12])

In [93]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x3 = x%3 ==0
x4=x%4==1
x5=(x%3==0)&(x%4==1)    # == np.logical_and(x%3==0,x%4==1)


array([9])

In [168]:
3*np.eye(5,5,k=-1,dtype=int)+2*np.eye(5,5,k=0,dtype=int)+np.eye(5,5,k=1,dtype=int)


array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [10]:
from numpy import random
n=10 * random.random_sample(size=(5,6))
n.max()         # 전체 최댓값
n.sum(axis=1)   # 각 행의 합
np.max(n, axis=1) # 각 행의 최댓값
np.mean(n,axis=0) # 각 열의 평균
np.min(n,axis=0)  # 각 열의 최솟값


In [5]:
n=np.array([[ 1, 2, 3, 4],
            [ 46, 99, 100, 71],
            [ 81, 59, 90, 100]])

a=np.argsort(n)[1,::-1]
n=n[:,a]
n


array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [14]:
n=np.random.randint(1,7,size=100)
print(n.mean())

#dice array에서의 고유값
np.unique(n)
# 고유값 및 갯수
np.unique(n,return_counts=True)

un,cu=np.unique(n,return_counts=True)
dict(zip(un,cu))

3.66


{1: 13, 2: 15, 3: 17, 4: 17, 5: 24, 6: 14}

In [20]:
#정규분포
rate=np.random.normal(0,0.01,5)
price=10000
for  i in range(250):
    price=np.round(price*(1+rate[i]))
    print(int(price),end=" ")

9826 9776 9956 10026 9904 

IndexError: index 5 is out of bounds for axis 0 with size 5

2.180543211159825